<?php
/**
 * User: Administrator
 */
class Controller_Index extends Blog_Web
{
    protected $layout = 'index';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function IndexAction()
    {
        $this -> display("index/index");
    }
}