<?php
/**
 * User: lidc
 * 首页
 */
class Controller_Index extends Web
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function IndexAction()
    {
        Header("Location: /user/index");
    }

}