<?php
/**
 * User: Administrator
 */

class Controller_Login extends Blog_Web
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function LoginAction()
    {
        $this->display('login/login');
    }


}